name: Remove 'Awaiting Response' label when PR is updated
on:
  issue_comment:
    types: [created, edited]
  pull_request_review:
    types: [edited]
  pull_request:
    types: [edited]

jobs:
  apply-label:
    if: contains( github.event.pull_request.labels.*.name, 'Awaiting Response')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.removeLabel({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              name: 'Awaiting Response'
            })
